import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeading } from "@/components/PageHeading";
import { StatusPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FileLock2, Loader2, ShieldAlert, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";

const presidentialRoles = ["national_president", "presidential_council"];

export default function CommandBrief() {
  const { user } = useAuth();
  const [sourceSummary, setSourceSummary] = useState("");
  const [date] = useState(() => new Date());
  const coverageStart = useMemo(() => new Date(date.getTime() - 24 * 60 * 60 * 1000), [date]);
  const canAccess = presidentialRoles.includes(user?.docRole || "");
  const briefs = trpc.doc.commandBriefs.useQuery({ isTestMode: false }, { enabled: canAccess });
  const utils = trpc.useUtils();
  const generate = trpc.doc.generateCommandBrief.useMutation({ onSuccess: () => utils.doc.commandBriefs.invalidate({ isTestMode: false }) });
  const create = trpc.doc.createCommandBrief.useMutation({ onSuccess: id => { setSourceSummary(""); generate.mutate({ id }); } });
  if (!canAccess) return <div className="mx-auto max-w-5xl"><PageHeading eyebrow="Executive control" title="Presidential Command Brief" description="This confidential executive module is available only to the National President and formally authorised Presidential Council users." /><div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 text-sm leading-6 text-amber-950"><ShieldAlert className="mb-3 h-5 w-5" />Your current Digital Operations Centre role does not include Command Brief access. This does not change your access to assigned operational modules.</div></div>;
  return <div className="mx-auto max-w-7xl"><PageHeading eyebrow="Module 1 · Executive control" title="Presidential Command Brief" description="A confidential decision-and-exception brief. It surfaces only material that requires presidential attention and remains a draft until authorised human review."><div className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-bold uppercase tracking-[.12em] text-emerald-800">Confidential draft control</div></PageHeading>
    <div className="grid gap-7 xl:grid-cols-[.95fr_1.05fr]"><section className="rounded-3xl bg-slate-950 p-7 text-white shadow-[0_30px_80px_-45px_rgba(15,23,42,.9)]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400 text-slate-950"><FileLock2 className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-300">New controlled source</p><h2 className="font-serif text-2xl">Prepare a draft brief</h2></div></div><p className="mt-5 text-sm leading-6 text-slate-300">Provide only authorised operational sources. The agent will prepare a draft briefing; it will not send a brief, direct officers, approve a decision, or alter an action.</p><div className="mt-6"><Label htmlFor="brief-source" className="text-slate-100">Authorised source summary</Label><Textarea id="brief-source" value={sourceSummary} onChange={event => setSourceSummary(event.target.value)} className="mt-2 min-h-56 border-slate-700 bg-white/5 text-white placeholder:text-slate-500" placeholder="Paste approved action, decision, risk, deadline, and exception information with owners and dates. Do not include unnecessary restricted information." /></div>{create.error || generate.error ? <p className="mt-3 text-sm text-rose-300">{create.error?.message || generate.error?.message}</p> : null}<Button onClick={() => create.mutate({ coverageStart, coverageEnd: date, sourceSummary, isTestMode: false })} disabled={sourceSummary.trim().length < 20 || create.isPending || generate.isPending} className="mt-5 bg-emerald-400 text-slate-950 hover:bg-emerald-300">{create.isPending || generate.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}Create confidential draft</Button><p className="mt-5 text-xs leading-5 text-slate-400">Human authority remains final. The command brief does not issue instructions or change operational ownership.</p></section>
      <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_20px_60px_-45px_rgba(15,23,42,.4)]"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Executive draft register</p><h2 className="mt-1 font-serif text-2xl text-slate-950">Recent command briefs</h2></div><StatusPill status="draft_ready" /></div>{briefs.isLoading ? <div className="p-8 text-sm text-slate-500">Loading confidential draft register…</div> : !briefs.data?.length ? <div className="p-10 text-center"><p className="font-medium text-slate-800">No Command Brief drafts have been created.</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">Create a source record only when there is a disciplined executive reporting requirement.</p></div> : <div className="divide-y divide-slate-100">{briefs.data.map(brief => <details key={brief.id} className="group px-6 py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><div><p className="font-medium text-slate-900">Coverage ending {new Date(brief.coverageEnd).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{brief.statusReason || "No status note."}</p></div><StatusPill status={brief.status} /></summary>{brief.draftBody ? <article className="prose prose-slate mt-5 max-w-none whitespace-pre-wrap border-t border-slate-100 pt-5 text-sm leading-6">{brief.draftBody}</article> : null}</details>)}</div>}</section>
    </div></div>;
}
