import { PageHeading } from "@/components/PageHeading";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BrainCircuit, Network, ShieldCheck } from "lucide-react";
import { civicAwarenessModel } from "@shared/civicAwareness";
import { intelligentDevelopmentEnvironment } from "@shared/intelligentDevelopmentEnvironments";

export default function CommunityIntelligence() {
  const topology = trpc.development.topology.useQuery();
  if (topology.isLoading || !topology.data) return <div className="text-sm text-slate-500">Loading approved community intelligence structure…</div>;

  return <div className="mx-auto max-w-6xl space-y-7">
    <PageHeading eyebrow="Development & community" title="Community intelligence" description="ISEYC’s approved grassroots accountability backbone and Responsibility Pillars, structured for responsible listening, verification, development, and escalation." />

    <Card className="border-slate-900 bg-slate-950 text-slate-100"><CardContent className="flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><Network className="mt-1 h-6 w-6 text-emerald-300" /><div><p className="font-serif text-2xl">From street intelligence to responsible leadership</p><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Street Representatives report upward. Line and Ward Coordinators aggregate and verify. Central Leadership provides oversight and escalation. The National President receives reviewed, summarised intelligence through the Presidential Command Brief.</p></div></div><Badge className="w-fit bg-emerald-300 text-slate-950 hover:bg-emerald-300">Human review required</Badge></CardContent></Card>

    <section><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">4-tier grassroots structure</p><div className="mt-4 grid gap-4 md:grid-cols-4">{topology.data.tiers.map(tier => <Card key={tier.id} className="relative overflow-hidden"><CardContent className="p-5"><span className="text-xs font-bold text-emerald-700">Tier {tier.hierarchyOrder}</span><h2 className="mt-4 font-serif text-xl text-slate-950">{tier.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{tier.description}</p></CardContent></Card>)}</div></section>

    <section><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">7 Responsibility Pillars</p><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{topology.data.pillars.map(pillar => <Card key={pillar.id}><CardContent className="p-5"><span className="text-xs font-bold text-emerald-700">Pillar {pillar.responsibilityOrder}</span><h2 className="mt-3 font-serif text-xl text-slate-950">{pillar.name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{pillar.description}</p></CardContent></Card>)}</div></section>

    <section><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">Key departments</p><Card className="mt-4 border-emerald-100 bg-emerald-50/50"><CardContent className="p-6"><div className="flex gap-4"><BrainCircuit className="mt-1 h-6 w-6 shrink-0 text-emerald-700" /><div><h2 className="font-serif text-2xl text-emerald-950">{intelligentDevelopmentEnvironment.name}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-950/80">{intelligentDevelopmentEnvironment.definition}</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2">{intelligentDevelopmentEnvironment.operatingElements.map(element => <div key={element.title} className="rounded-xl border border-emerald-100 bg-white p-4"><p className="font-medium text-slate-900">{element.title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{element.description}</p></div>)}</div><div className="mt-5 space-y-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">{intelligentDevelopmentEnvironment.safeguards.map(rule => <p key={rule}>{rule}</p>)}</div></CardContent></Card></section>

    <section><p className="text-xs font-bold uppercase tracking-[.14em] text-emerald-700">National awareness layer</p><Card className="mt-4 border-emerald-100 bg-emerald-50/60"><CardContent className="p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><BrainCircuit className="mt-1 h-6 w-6 shrink-0 text-emerald-700" /><div><h2 className="font-serif text-2xl text-emerald-950">{civicAwarenessModel.connectionName}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-emerald-900/75">{civicAwarenessModel.connectionDescription}</p></div></div><a href={civicAwarenessModel.civicBrainUrl} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-2 text-sm font-medium text-emerald-800 hover:text-emerald-950">Open Civic Brain <ArrowUpRight className="h-4 w-4" /></a></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{civicAwarenessModel.awarenessLevels.map(level => <div key={level.title} className="rounded-xl border border-emerald-100 bg-white p-4"><p className="font-medium text-slate-900">{level.title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{level.purpose}</p></div>)}</div><div className="mt-6 flex flex-wrap items-center gap-2">{civicAwarenessModel.controlledFlow.map((step, index) => <span key={step} className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.08em] text-emerald-800"><span className="rounded-full bg-emerald-100 px-2 py-1">{step}</span>{index < civicAwarenessModel.controlledFlow.length - 1 ? <span className="text-emerald-300">→</span> : null}</span>)}</div><div className="mt-5 space-y-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">{civicAwarenessModel.safeguards.map(rule => <p key={rule}>{rule}</p>)}</div></CardContent></Card></section>

    <div className="flex gap-3 rounded-xl border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-600"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-emerald-700" />These structures are institutional intelligence systems, not automated enforcement tools. Signals and public education material require source traceability and accountable human review.</div>
  </div>;
}
