import { PageHeading } from "@/components/PageHeading";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, HeartHandshake, MapPinned, UserCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function DevelopmentGovernance() {
  const queue = trpc.development.governanceQueue.useQuery();
  const utils = trpc.useUtils();
  const [mentors, setMentors] = useState<Record<number, string>>({});
  const [focus, setFocus] = useState<Record<number, string>>({});
  const confirm = trpc.development.confirmParticipationRecord.useMutation({ onSuccess: () => { utils.development.governanceQueue.invalidate(); toast.success("Participation has been confirmed."); }, onError: err => toast.error(err.message) });
  const approve = trpc.development.approveMentorship.useMutation({ onSuccess: () => { utils.development.governanceQueue.invalidate(); toast.success("Mentorship relationship has been human-approved."); }, onError: err => toast.error(err.message) });
  const confirmAffiliation = trpc.development.confirmCommunityAffiliation.useMutation({ onSuccess: () => { utils.development.governanceQueue.invalidate(); toast.success("Community affiliation confirmed under accountable human review."); }, onError: err => toast.error(err.message) });

  if (queue.isLoading || !queue.data) return <div className="text-sm text-slate-500">Loading development governance queue…</div>;

  return <div className="mx-auto max-w-6xl space-y-7">
    <PageHeading eyebrow="Governance" title="Development continuity review" description="Confirm contribution records, self-declared community affiliations, and mentorship relationships. These controls create accountable continuity; they do not automate assessment, promotion, matching, role assignment, or authority." />
    <div className="grid gap-6 lg:grid-cols-2">
      <Card><CardContent className="p-6"><div className="flex items-center gap-3"><BadgeCheck className="h-5 w-5 text-emerald-700" /><div><p className="font-medium text-slate-900">Participation awaiting confirmation</p><p className="text-sm text-slate-500">Only confirmed records become part of a member’s visible contribution history.</p></div></div><div className="mt-5 space-y-3">{queue.data.pendingParticipation.length ? queue.data.pendingParticipation.map(item => <div key={item.record.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium text-slate-900">{item.record.title}</p><p className="mt-1 text-sm text-slate-600">{item.member?.name || "Member"} · {item.record.participationType.replaceAll("_", " ")}</p>{item.record.detail ? <p className="mt-2 text-sm text-slate-500">{item.record.detail}</p> : null}<Button className="mt-3" size="sm" onClick={() => confirm.mutate({ participationId: item.record.id })} disabled={confirm.isPending}>Confirm record</Button></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No participation records are awaiting review.</p>}</div></CardContent></Card>

      <Card><CardContent className="p-6"><div className="flex items-center gap-3"><UserCheck className="h-5 w-5 text-emerald-700" /><div><p className="font-medium text-slate-900">Mentorship requests</p><p className="text-sm text-slate-500">Approve only after a responsible human has agreed the mentor, scope, and appropriate boundary.</p></div></div><div className="mt-5 space-y-3">{queue.data.mentorshipRequests.length ? queue.data.mentorshipRequests.map(item => <div key={item.relationship.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium text-slate-900">{item.member?.name || "Member"}</p><p className="mt-1 text-sm text-slate-600">{item.relationship.agreedFocus || "No focus was recorded."}</p><div className="mt-3 space-y-2"><Label>Approved mentor</Label><Select value={mentors[item.relationship.id]} onValueChange={value => setMentors(current => ({ ...current, [item.relationship.id]: value }))}><SelectTrigger><SelectValue placeholder="Select authorised mentor" /></SelectTrigger><SelectContent>{queue.data.mentorCandidates.map(candidate => <SelectItem key={candidate.id} value={String(candidate.id)}>{candidate.name || candidate.email || `Officer #${candidate.id}`}</SelectItem>)}</SelectContent></Select><Textarea value={focus[item.relationship.id] || ""} onChange={event => setFocus(current => ({ ...current, [item.relationship.id]: event.target.value }))} placeholder="Agreed developmental focus" /></div><Button className="mt-3" size="sm" disabled={!mentors[item.relationship.id] || approve.isPending} onClick={() => approve.mutate({ relationshipId: item.relationship.id, mentorUserId: Number(mentors[item.relationship.id]), agreedFocus: focus[item.relationship.id] || undefined })}><HeartHandshake className="mr-2 h-4 w-4" />Approve relationship</Button></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No mentorship requests are awaiting review.</p>}</div></CardContent></Card>

      <Card className="lg:col-span-2"><CardContent className="p-6"><div className="flex items-center gap-3"><MapPinned className="h-5 w-5 text-emerald-700" /><div><p className="font-medium text-slate-900">Self-declared community affiliations</p><p className="text-sm text-slate-500">Confirm only an active-consent selection from the approved grassroots hierarchy. Confirmation recognises a member’s stated connection; it does not create an appointment, operational authority, or leadership role.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{queue.data.selfDeclaredAffiliations.length ? queue.data.selfDeclaredAffiliations.map(item => <div key={item.affiliation.id} className="rounded-xl border border-slate-200 p-4"><p className="font-medium text-slate-900">{item.member?.name || "Member"}</p><p className="mt-1 text-sm font-semibold text-emerald-800">{item.tier?.name || "Approved tier unavailable"}</p><p className="mt-2 text-xs leading-5 text-slate-500">Self-declared affiliation awaiting accountable human confirmation. This does not assign a post or authority.</p><Button className="mt-3" size="sm" variant="outline" onClick={() => confirmAffiliation.mutate({ affiliationId: item.affiliation.id })} disabled={confirmAffiliation.isPending}>Confirm affiliation</Button></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No self-declared affiliations are awaiting review.</p>}</div></CardContent></Card>
    </div>
  </div>;
}
