import { useAuth } from "@/_core/hooks/useAuth";
import { PageHeading } from "@/components/PageHeading";
import { StatusPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, ChevronLeft, ShieldCheck } from "lucide-react";
import { useLocation, useRoute } from "wouter";

export default function MediaDraftReview() {
  const [, params] = useRoute("/media/:id"); const id = Number(params?.id); const [, setLocation] = useLocation(); const { user } = useAuth(); const detail = trpc.doc.contentDraft.useQuery({ id }, { enabled: Number.isFinite(id) }); const utils = trpc.useUtils(); const review = trpc.doc.reviewContentDraft.useMutation({ onSuccess: () => { utils.doc.contentDraft.invalidate({ id }); utils.doc.contentQueue.invalidate(); } }); const item = detail.data; const draft = item?.draftJson as Record<string, unknown> | null | undefined;
  if (!item) return <div className="mx-auto max-w-6xl p-8 text-sm text-slate-500">Loading content draft…</div>;
  const isAdmin = user?.role === "admin";
  return <div className="mx-auto max-w-6xl"><PageHeading eyebrow="Module 3 · Human review" title={item.title} description="This is a traceable content draft. Approval means approved for independent publication; it does not post, schedule, send, or reply externally."><Button variant="outline" onClick={() => setLocation("/media")}><ChevronLeft className="mr-2 h-4 w-4" />Return to queue</Button>{isAdmin && draft ? <><Button variant="outline" onClick={() => review.mutate({ id, decision: "revision_requested" })}>Request revision</Button><Button className="bg-emerald-700 text-white hover:bg-emerald-800" onClick={() => review.mutate({ id, decision: "approved_for_publication" })}><CheckCircle2 className="mr-2 h-4 w-4" />Approve for publication</Button></> : null}</PageHeading>
    <div className="mb-6 flex flex-wrap items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-950"><AlertTriangle className="h-4 w-4" /><strong>{item.isTestMode ? "Test isolation control:" : "Publication control:"}</strong>{item.isTestMode ? " This is an isolated test record. It cannot enter the live queue or initiate external publication." : " No post, message, reply, schedule, outreach, or external action has been performed by this system."}</div><div className="grid gap-6 xl:grid-cols-[1fr_300px]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_20px_60px_-45px_rgba(15,23,42,.4)]"><div className="flex items-center justify-between gap-4 border-b border-slate-100 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-500">Draft package</p><p className="mt-1 text-sm text-slate-600">{item.objective}</p></div><StatusPill status={item.status} /></div>{draft ? <div className="mt-6 space-y-7">{[["X", draft.xDraft],["WhatsApp", draft.whatsappDraft],["LinkedIn", draft.linkedInDraft],["Suggested response", draft.responseSuggestion]].map(([label, value]) => <article key={String(label)}><h2 className="font-serif text-xl text-slate-900">{String(label)}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{String(value || "Not requested.")}</p></article>)}<article><h2 className="font-serif text-xl text-slate-900">Outreach research</h2><pre className="mt-3 overflow-auto rounded-xl bg-slate-50 p-4 text-xs leading-6 text-slate-700">{JSON.stringify(draft.outreachResearch || [], null, 2)}</pre></article></div> : <div className="p-10 text-center text-sm text-slate-500">This source has not generated a draft package. It may be awaiting approval or governance review.</div>}</section><aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><ShieldCheck className="h-5 w-5 text-emerald-700" /><h2 className="mt-3 font-serif text-xl text-slate-900">Source and control</h2><dl className="mt-4 space-y-3 text-sm"><Item label="Source" value={item.sourceReference} /><Item label="Approval" value={item.sourceApprovalStatus.replaceAll("_", " ")} /><Item label="Sensitivity" value={item.sensitivity} /><Item label="Channels" value={JSON.stringify(item.channelsJson)} /></dl></section><section className="rounded-2xl bg-slate-950 p-5 text-slate-50"><p className="text-xs font-bold uppercase tracking-[.13em] text-emerald-300">Reviewer instruction</p><p className="mt-3 text-sm leading-6 text-slate-300">Use approval only when the source is appropriate for external communication. Publication remains a separate, independent human action through ISEYC’s approved accounts.</p></section></aside></div></div>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-bold uppercase tracking-[.11em] text-slate-400">{label}</dt><dd className="mt-1 break-words text-slate-700">{value}</dd></div>; }
