import { PageHeading } from "@/components/PageHeading";
import { StatusPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Clock3, Inbox, RefreshCw } from "lucide-react";
import { useLocation } from "wouter";

export default function Queue() {
  const [, setLocation] = useLocation();
  const queue = trpc.meeting.queue.useQuery({ isTestMode: false });
  const items = queue.data || [];
  return <div className="mx-auto max-w-7xl"><PageHeading eyebrow="Live records" title="Intake queue" description="Live submissions remain separated from test materials and progress only through controlled status changes."><Button variant="outline" onClick={() => queue.refetch()}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></PageHeading>
    <div className="mb-6 grid gap-3 sm:grid-cols-3"><Metric label="Awaiting consolidation" value={items.filter(item => item.status === "pending_consolidation").length} tone="amber" /><Metric label="Drafts ready" value={items.filter(item => ["draft_ready", "under_review"].includes(item.status)).length} tone="violet" /><Metric label="Approved records" value={items.filter(item => item.status === "approved").length} tone="green" /></div>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_20px_60px_-45px_rgba(15,23,42,.45)]"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-700"><Inbox className="h-4 w-4" /></span><div><h2 className="font-serif text-xl text-slate-900">Current submissions</h2><p className="text-xs text-slate-500">All statuses are audit-recorded.</p></div></div></div>
      {queue.isLoading ? <div className="p-10 text-sm text-slate-500">Loading controlled queue…</div> : !items.length ? <div className="p-12 text-center"><Clock3 className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 font-medium text-slate-700">No live meeting submissions yet.</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">A controlled intake will remain evidence-linked and non-authoritative until authorised human review is complete.</p><Button className="mt-5 bg-emerald-400 text-slate-950 hover:bg-emerald-300" onClick={() => setLocation("/intake")}>Create a controlled intake</Button></div> : <div className="divide-y divide-slate-100">{items.map(item => <button key={item.id} onClick={() => setLocation(`/review/${item.id}`)} className="group flex w-full items-center gap-5 px-6 py-5 text-left transition-colors hover:bg-slate-50"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-slate-900">{item.meetingTitle}</span><StatusPill status={item.status} /></div><p className="mt-1 truncate text-sm text-slate-500">{item.conveningBody || "Convening body not recorded"} · {item.meetingDate || "Date not recorded"}</p><p className="mt-2 text-xs text-slate-500">{item.statusReason || "No additional status note."}</p></div><div className="hidden text-right text-xs text-slate-500 sm:block"><div>Submitted</div><div className="mt-1 font-medium text-slate-700">{new Date(item.createdAt).toLocaleDateString()}</div></div><ArrowRight className="h-4 w-4 text-slate-300 transition-transform group-hover:translate-x-1 group-hover:text-emerald-700" /></button>)}</div>}</section>
  </div>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: "amber" | "violet" | "green" }) { const colour = { amber: "border-amber-100 bg-amber-50", violet: "border-violet-100 bg-violet-50", green: "border-emerald-100 bg-emerald-50" }[tone]; return <div className={`rounded-xl border p-4 ${colour}`}><p className="text-xs font-semibold uppercase tracking-[.13em] text-slate-500">{label}</p><p className="mt-1 font-serif text-3xl text-slate-900">{value}</p></div>; }
